In [27]:
import numpy as np
with open("../files/p096_sudoku.txt", "r") as f:
    lines = f.readlines()
lines = [str(line).replace("\n", "") for line in lines]

grids = []

while len(lines) > 0:
    grids += [lines[1:10]]
    lines = lines[10:]

for grid in grids:
    for i, line in enumerate(grid):
        grid[i] = list(line)

grids = [np.array(grid) for grid in grids]

grids = [grids[0]]  #delete this once it's time to test the code on all of them

def validGrid(grid):
    checks = []
    for i in range(9):
        checks += [grid[i, :]]

    for i in range(9):
        checks += [grid[:, i]]

    for r in range(0, 9, 3):
        for c in range(0, 9, 3):
            checks += [grid[r: r + 3, c: c + 3].flatten()]


    
    return np.array(checks)

for grid in grids:
    matrix = [[int(num) for num in row] for row in grid]
    possible = np.array([[[1 for x in range(9)] for y in range(9)] for z in range(9)])
    for y, row in enumerate(matrix):
        for x, num in enumerate(row):
            if num > 0:
                #possible[y, :, num-1] = [0 for i in range(9)]
                possible[:, x, num-1] = [0 for i in range(9)]
    
    print(possible)
                
            


[[[1 1 1 1 1 1 0 0 0]
  [1 1 1 1 1 1 1 1 1]
  [0 0 0 1 0 0 1 0 1]
  [0 0 0 1 1 0 0 0 1]
  [0 0 1 1 1 1 1 1 1]
  [1 0 0 1 0 0 1 0 0]
  [1 0 0 0 0 0 1 1 0]
  [1 1 1 1 1 1 1 1 1]
  [0 1 1 1 1 1 1 0 0]]

 [[1 1 1 1 1 1 0 0 0]
  [1 1 1 1 1 1 1 1 1]
  [0 0 0 1 0 0 1 0 1]
  [0 0 0 1 1 0 0 0 1]
  [0 0 1 1 1 1 1 1 1]
  [1 0 0 1 0 0 1 0 0]
  [1 0 0 0 0 0 1 1 0]
  [1 1 1 1 1 1 1 1 1]
  [0 1 1 1 1 1 1 0 0]]

 [[1 1 1 1 1 1 0 0 0]
  [1 1 1 1 1 1 1 1 1]
  [0 0 0 1 0 0 1 0 1]
  [0 0 0 1 1 0 0 0 1]
  [0 0 1 1 1 1 1 1 1]
  [1 0 0 1 0 0 1 0 0]
  [1 0 0 0 0 0 1 1 0]
  [1 1 1 1 1 1 1 1 1]
  [0 1 1 1 1 1 1 0 0]]

 [[1 1 1 1 1 1 0 0 0]
  [1 1 1 1 1 1 1 1 1]
  [0 0 0 1 0 0 1 0 1]
  [0 0 0 1 1 0 0 0 1]
  [0 0 1 1 1 1 1 1 1]
  [1 0 0 1 0 0 1 0 0]
  [1 0 0 0 0 0 1 1 0]
  [1 1 1 1 1 1 1 1 1]
  [0 1 1 1 1 1 1 0 0]]

 [[1 1 1 1 1 1 0 0 0]
  [1 1 1 1 1 1 1 1 1]
  [0 0 0 1 0 0 1 0 1]
  [0 0 0 1 1 0 0 0 1]
  [0 0 1 1 1 1 1 1 1]
  [1 0 0 1 0 0 1 0 0]
  [1 0 0 0 0 0 1 1 0]
  [1 1 1 1 1 1 1 1 1]
  [0 1 1 1 1 1 1 0 0]]

